/**
* @File Name : BatchClassTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 29, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 29, 2025 |   | Initial Version
**/

public class BatchClassTest {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}